In [1]:
import numpy
from sklearn import linear_model 

In [3]:
X = numpy.array([3.78, 2.44, 2.09, 0.14, 1.72, 1.65, 4.92, 4.37, 4.96, 4.52, 3.69, 5.88]).reshape(-1, 1)
print(X)

[[3.78]
 [2.44]
 [2.09]
 [0.14]
 [1.72]
 [1.65]
 [4.92]
 [4.37]
 [4.96]
 [4.52]
 [3.69]
 [5.88]]


In [4]:
y = numpy.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [5]:
logr = linear_model.LogisticRegression()
logr.fit(X, y)

LogisticRegression()

In [8]:
predicted = logr.predict(numpy.array([7.56]).reshape(-1,1))
print(predicted)

[1]


In [9]:
log_odds = logr.coef_
odds = numpy.exp(log_odds)
odds 
# This tells us that as the size of a tumor increases by 1mm the odds of it being a tumor increases by 4x.

array([[4.03541657]])

In [10]:
def logit2prob(logr, x):
    log_odds = logr.coef_ * x + logr.intercept_
    odds = numpy.exp(log_odds)
    probability = odds / (1 + odds)
    return(probability)   

In [11]:
print(logit2prob(logr, X))

[[0.60749955]
 [0.19268876]
 [0.12775886]
 [0.00955221]
 [0.08038616]
 [0.07345637]
 [0.88362743]
 [0.77901378]
 [0.88924409]
 [0.81293497]
 [0.57719129]
 [0.96664243]]
